### ISSUE TITLE
Can't launch the VM: fail to add MMCONFIG information, can’t access extended PCI configuration space under this bridge

### ISSUE THREAD

**Issue by brain235** [Rhydon1337/linux-kernel-debugging#1]
Thank you for this awesome tutorial, there are not much information on Linux debugging with qemu + vscode.

Unfortunately I get stuck on launching the vm.
`sudo qemu-system-x86_64 -enable-kvm -cpu host -s -kernel bzImage -m 2048 -hda rootfs.qcow2 -append "root=/dev/sda rw nokaslr" -net nic,model=virtio -net user,hostfwd=tcp::5555-:22`

I’m on:
Ubuntu Kubuntu 22.04.1 LTS
Linux 5.15.0-52
qemu 6.2.0
buildroot-2022.08

error Message:
```
acpi PNP0A03:00: _OSC: OS supports [ASPM ClockPM Segments HPX-Type3
acpi PNP0A03:00: fail to add MMCONFIG information, can’t access extended PCI configuration space under this bridge.
PCI host bridge to bus 0000:00
```
KVM should be fine:
```
~$kvm-ok
INFO: /dev/kvm exists 
KVM acceleration can be used
```

Do you have any idea, what I can do?

Full screenshot:
![image](https://user-images.githubusercontent.com/96888264/199713442-6f6740a3-2947-4466-add8-352f4a63486d.png)

**Comment by brain235** [comment]
I asked on the mailing list of qemu: https://lists.nongnu.org/archive/html/qemu-discuss/2022-11/msg00010.html

And on Stackoverflow: https://stackoverflow.com/questions/74320731/kernel-compile-with-builtroot-and-run-it-in-qemu-vm-fail-to-add-mmconfig-inform

Nobody answered. I would be very pleased if you find time, to take a quick look.

**Comment by aBraM-aBraM** [comment]
try running `export PATH="/home/<user>/path/to/buildroot/output/host/bin:${PATH}"`
before running qemu

if it still doesn't work try merging the flags into the script buildroot generated in   "/home/<user>/path/to/buildroot/output/images/start-qemu.sh"
